# Generated by Django 5.1.7 on 2025-04-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0002_tier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
