# Generated by Django 5.1.7 on 2025-04-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0003_delete_tier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Karakter',
        ),
    ]
