# Generated by Django 5.1.7 on 2025-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0004_rename_character_karakter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karakter',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
