# Generated by Django 5.1.7 on 2025-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0005_alter_karakter_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karakter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
