# Generated by Django 5.1.7 on 2025-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0006_alter_karakter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karakter',
            name='description',
        ),
        migrations.AddField(
            model_name='karakter',
            name='tier',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
