# Generated by Django 5.1.7 on 2025-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0007_remove_karakter_description_karakter_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Tank', 'Tank'), ('Damage', 'Damage'), ('Support', 'Support')], max_length=10)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
