# Generated by Django 5.1.7 on 2025-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0008_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
