# Generated by Django 5.1.7 on 2025-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0009_remove_hero_difficulty_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
